language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

script:
    - phpize
    - ./configure
    - make
    - php -n run-tests.php -n -d extension_dir=./modules/ -d extension=apcu.so -d apc.enable=1 -d apc.enable_cli=1 -p `phpenv which php` --show-diff --set-timeout 120
    - phpize --clean
    - phpize
    - ./configure --disable-apcu-rwlocks
    - make
    - php -n run-tests.php -n -d extension_dir=./modules/ -d extension=apcu.so -d apc.enable=1 -d apc.enable_cli=1 -p `phpenv which php` --show-diff --set-timeout 120
